### ISSUE TITLE
皮卡鱼象棋引擎

### ISSUE THREAD

**Issue by shuangqiao999** [nguyenpham/XiangqiTestSuites#1]
你好 有个皮卡鱼的象棋项目 你有兴趣参加吗？项目地址:https://github.com/PikaCat-OuO/Pikafish

**Comment by calcitem** [comment]
你好！为啥不基于 https://github.com/ianfab/Faity-Stockfish 项目来做呢？基于鳕鱼实现了象棋引擎，已经很成熟了。支持 NNUE。
